# Generated by Django 5.1.6 on 2025-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Res_name", models.CharField(max_length=100)),
                ("Food_cat", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                (
                    "img",
                    models.URLField(
                        default="https://images.rawpixel.com/image_800/cHJpdmF0ZS9zdGF0aWMvaW1hZ2Uvd2Vic2l0ZS8yMDIyLTA0L2xyL3B4ODM4MjQ5LWltYWdlLWt3dnV6aTE5LmpwZw.jpg"
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
        ),
    ]
